web:
    build: ./widu-community-web
    ports:
     - "80:80"
    links:
     - main

#hovyubot:
#    build: ./widu-community-telegram
#    links:
#     - main
#    external_links:
#     - mongodockercompose_db_1

main:
    build: ./widu-community-server
    external_links:
     - mongodockercompose_db_1
